//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KULLANICIID { get; set; }
        public string KULLANICIADI { get; set; }
        public string ISIM { get; set; }
        public string SOYISIM { get; set; }
        public int SIFRE { get; set; }
    }
}
